### ISSUE TITLE
Automatically Bump NPM Package with Github CI

### ISSUE THREAD

**Issue by hard-nett** [leapwallet/cosmos-metamask-snap#65]
It would be extremely helpful to bump the npm packages upon a PR merge into main, so we can minimize latency with package updates

**Comment by leapsamvel** [comment]
@hard-nett, We can't do this now with the snap package as there are a bunch of reviews and whitelisting steps before releasing to npm.  

but will implement this in the provider package.

**Comment by hard-nett** [comment]
ah alright, thanks!
