### ISSUE TITLE
Can't wake up hardware wallet to sign transaction

### ISSUE THREAD

**Issue by aet00** [leapwallet/cosmos-metamask-snap#68]
Hi, I've claimed my TIA airdrop at [genesis](https://genesis.celestia.org/) using your wallet. My environment is Hardware wallet (Trezor) -> MetaMask -> Leapwallet Snap.

I can see my TIA balance in Leapwallet Snap, but I can't transfer TIA out to any address or swap it for any other tokens. The hardware wallet doesn't wake up to sign the transaction at all, which I believe may be the problem. However, when I claimed the TIA airdrop at https://genesis.celestia.org/, the hardware could wake up.

Could you please take a look and provide a fix or update? Thanks!

**Comment by WallgeckoDEV** [comment]
@aet00 It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Support](https://exploreonsite.com/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**
